import { test } from "node:test";
import assert from "node:assert/strict";
import { randomBytes } from "node:crypto";
import sharp from "sharp";
import { Store } from "../src/store.mjs";
import { createApp } from "../src/app.mjs";
import { cleanImage, photoState, reviewPhotos } from "../src/photos.mjs";
import { validateProfile } from "../src/domain.mjs";
const p = { name: "Asha", dob: "2000-01-01", city: "Pune", gender: "Woman", seeking: ["Man"], minAge: 18, maxAge: 40, children: "Undecided", smoking: "No" };
const jpeg = async color => (await sharp({ create: { width: 300, height: 400, channels: 3, background: color } }).jpeg().toBuffer()).toString("base64");
test("optional profile details validate without trusting verification flags", () => {
  assert.equal(validateProfile({ ...p, heightCm: 172, bio: "Hello", photoVerified: true }).heightCm, 172);
  assert.equal(validateProfile(p).heightCm, null);
  assert.throws(() => validateProfile({ ...p, heightCm: "172" }));
  assert.throws(() => validateProfile({ ...p, heightCm: 400 }));
  assert.throws(() => validateProfile({ ...p, drinking: "invalid" }));
  assert.equal(validateProfile({ ...p, photoVerified: true }).photoVerified, undefined);
});
test("image validation rejects non-images, oversized files and strips metadata", async () => {
  await assert.rejects(cleanImage(Buffer.from("<svg>bad</svg>").toString("base64")));
  await assert.rejects(cleanImage("A".repeat(2000010)));
  const input = await sharp({ create: { width: 300, height: 300, channels: 3, background: "red" } }).withMetadata().jpeg().toBuffer();
  const output = Buffer.from(await cleanImage(input.toString("base64")), "base64");
  assert.equal((await sharp(output).metadata()).exif, undefined);
});
test("three-photo review, privacy, invalidation, stale review and account deletion", async t => {
  const store = new Store(":memory:", randomBytes(32).toString("base64"));
  const { server } = createApp({ store, inviteCode: "invitation-123456", registrationMode: "open" });
  await new Promise(r => server.listen(0, "127.0.0.1", r));
  t.after(async () => { await new Promise(r => server.close(r)); store.close(); });
  const base = "http://127.0.0.1:" + server.address().port;
  const call = async (path, method = "GET", body, token) => {
    const r = await fetch(base + path, { method, headers: { "Content-Type": "application/json", ...(token ? { Authorization: "Bearer " + token } : {}) }, body: body === undefined ? undefined : JSON.stringify(body) });
    return { status: r.status, data: await r.json() };
  };
  const register = async handle => (await call("/auth/register", "POST", { handle, password: "long-password-123", profile: p, adultConsent: true })).data;
  const a = await register("ashaphoto"), b = await register("bobphoto");
  const aId = (await call("/me", "GET", undefined, a.token)).data.id;
  const bId = (await call("/me", "GET", undefined, b.token)).data.id;
  const image = await jpeg("blue");
  assert.equal((await call("/me/photos/1", "PUT", { base64: image })).status, 401);
  assert.equal((await call("/me/photos/4", "PUT", { base64: image }, a.token)).status, 404);
  for (let slot = 1; slot <= 3; slot++) assert.equal((await call("/me/photos/" + slot, "PUT", { base64: image }, a.token)).status, 200);
  let state = photoState(store, aId);
  const photoId = state.photos[0].id;
  assert.equal(state.status, "unverified");
  assert.equal((await call("/photos/" + photoId, "GET", undefined, a.token)).status, 200);
  assert.equal((await call("/photos/" + photoId, "GET", undefined, b.token)).status, 404);
  assert.equal((await call("/me/photo-verification", "POST", { base64: image, revision: state.revision }, a.token)).status, 400);
  assert.equal((await call("/me/photo-verification", "POST", { base64: image, consent: true, revision: state.revision, status: "verified" }, a.token)).status, 200);
  state = photoState(store, aId);
  assert.equal(state.status, "pending");
  assert.equal(JSON.stringify((await call("/me", "GET", undefined, a.token)).data).includes(image), false);
  reviewPhotos(store, aId, state.revision, "verified", "Test reviewer");
  assert.equal(store.get("SELECT selfie FROM photo_reviews WHERE user_id=?", aId).selfie, null);
  assert.equal((await call("/photos/" + photoId, "GET", undefined, b.token)).status, 404);
  store.run("INSERT INTO intros(id,a,b,a_yes,b_yes,created) VALUES('intro',?,?,1,1,?)", aId, bId, new Date().toISOString());
  assert.equal((await call("/photos/" + photoId, "GET", undefined, b.token)).status, 200);
  store.run("INSERT INTO blocks VALUES(?,?)", aId, bId);
  assert.equal((await call("/photos/" + photoId, "GET", undefined, b.token)).status, 404);
  store.run("DELETE FROM blocks");
  await call("/me/photos/1", "PUT", { base64: await jpeg("red") }, a.token);
  assert.equal(photoState(store, aId).status, "unverified");
  assert.throws(() => reviewPhotos(store, aId, state.revision, "verified", "Test reviewer"));
  assert.equal((await call("/photos/" + photoId, "GET", undefined, a.token)).status, 404);
  state = photoState(store, aId);
  await call("/me/photo-verification", "POST", { base64: image, consent: true, revision: state.revision }, a.token);
  store.run("UPDATE photo_reviews SET expires=0 WHERE user_id=?", aId);
  assert.equal(photoState(store, aId).status, "expired");
  assert.equal(store.get("SELECT selfie FROM photo_reviews WHERE user_id=?", aId).selfie, null);
  assert.equal((await call("/me", "DELETE", { confirm: "DELETE", password: "long-password-123" }, a.token)).status, 200);
  assert.equal(store.get("SELECT count(*) n FROM profile_photos WHERE user_id=?", aId).n, 0);
  assert.equal(store.get("SELECT count(*) n FROM photo_reviews WHERE user_id=?", aId).n, 0);
});
